package com.lpm.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Represents a specific loan product offered by the lending platform.
 * This entity stores information about the product's name, interest rate,
 * minimum and maximum loan amounts, and the standard loan tenure.
 */
@Entity
@Table(name = "LoanProduct")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LoanProduct {

    /**
     * The unique identifier for the loan product.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int loanProductId;

    /**
     * The name of the loan product (e.g., "Personal Loan", "Home Loan").
     */
    private String productName;

    /**
     * The annual interest rate for this loan product, expressed as a BigDecimal.
     */
    private BigDecimal interestRate;

    /**
     * The minimum loan amount that can be availed for this product, expressed as a BigDecimal.
     */
    private BigDecimal minAmount;

    /**
     * The maximum loan amount that can be availed for this product, expressed as a BigDecimal.
     */
    private BigDecimal maxAmount;

    /**
     * The standard loan tenure for this product, typically in months or years.
     */
    private int tenure;
}